# Generated by Django 6.0.6 on 2026-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=30, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="电话"),
        ),
    ]
